### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by stuhlmueller** [nwf/dyna#81]
I set up a fresh server on [EC2](http://aws.amazon.com/ec2/), of this type:

    Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-df6a8b9b
    m3.xlarge

Logged in:

    ssh -i mykeypair.pem ubuntu@.....compute.amazonaws.com

Executed the following commands:

    sudo apt-get update
    sudo apt-get install haskell-platform git make python-setuptools libncurses5-dev
    sudo easy_install ipython pygments
    cabal update
    git clone http://github.com/nwf/dyna
    cd dyna
    make

Ran into the following problem:

    ...
    Linking /tmp/trifecta-1.5-10290/trifecta-1.5/dist/setup/setup ...
    Configuring trifecta-1.5...
    Building trifecta-1.5...
    Preprocessing library trifecta-1.5...
    [ 1 of 13] Compiling Text.Trifecta.Util.Array ( src/Text/Trifecta/Util/Array.hs, dist/build/Text/Trifecta/Util/Array.o )
    [ 2 of 13] Compiling Text.Trifecta.Util.Combinators ( src/Text/Trifecta/Util/Combinators.hs, dist/build/Text/Trifecta/Util/Combinators.o )
    [ 3 of 13] Compiling Text.Trifecta.Util.IntervalMap ( src/Text/Trifecta/Util/IntervalMap.hs, dist/build/Text/Trifecta/Util/IntervalMap.o )
    [ 4 of 13] Compiling Text.Trifecta.Instances ( src/Text/Trifecta/Instances.hs, dist/build/Text/Trifecta/Instances.o )
    [ 5 of 13] Compiling Text.Trifecta.Delta ( src/Text/Trifecta/Delta.hs, dist/build/Text/Trifecta/Delta.o )
    [ 6 of 13] Compiling Text.Trifecta.Rope ( src/Text/Trifecta/Rope.hs, dist/build/Text/Trifecta/Rope.o )
    [ 7 of 13] Compiling Text.Trifecta.Util.It ( src/Text/Trifecta/Util/It.hs, dist/build/Text/Trifecta/Util/It.o )
    [ 8 of 13] Compiling Text.Trifecta.Highlight ( src/Text/Trifecta/Highlight.hs, dist/build/Text/Trifecta/Highlight.o )
    
    src/Text/Trifecta/Highlight.hs:46:15:
        Ambiguous occurrence `Comment'
        It could refer to either `Text.Blaze.Internal.Comment',
                                 imported from `Text.Blaze.Internal' at src/Text/Trifecta/Highlight.hs:35:1-26
                              or `Text.Parser.Token.Highlight.Comment',
                                 imported from `Text.Parser.Token.Highlight' at src/Text/Trifecta/Highlight.hs:36:1-34
    Failed to install trifecta-1.5
    cabal: Error: some packages failed to install:
    trifecta-1.5 failed during the building phase. The exception was:
    ExitFailure 1
    make: *** [deps] Error 1

Tried to work around it as follows:

    cabal install --constraint='blaze-markup <0.6.3' --user --enable-tests --only-dependencies .

This seemed successful at first:

    Resolving dependencies...
    Downloading blaze-markup-0.6.2.0...
    ...
    Loading package reflection-1.5.1.2 ... linking ... done.
    Loading package primitive-0.5.0.1 ... linking ... done.
    Loading package vector-0.10.0.1 ... linking ... done.
    Loading package lens-4.9.1 ... linking ... done.
    Loading package blaze-builder-0.3.3.4 ... linking ... done.
    Loading package blaze-markup-0.6.2.0 ... linking ... done.
    Loading package blaze-html-0.7.0.3 ... linking ... done.
    Loading package old-locale-1.0.0.5 ... linking ... done.
    Loading package time-1.4.0.1 ... linking ... done.
    Loading package unix-2.6.0.1 ... linking ... done.
    Loading package ansi-terminal-0.6.2.1 ... linking ... done.
    Loading package ansi-wl-pprint-0.6.7.2 ... linking ... done.
    [ 9 of 13] Compiling Text.Trifecta.Rendering ( src/Text/Trifecta/Rendering.hs, dist/build/Text/Trifecta/Rendering.o )
    [10 of 13] Compiling Text.Trifecta.Combinators ( src/Text/Trifecta/Combinators.hs, dist/build/Text/Trifecta/Combinators.o )
    [11 of 13] Compiling Text.Trifecta.Result ( src/Text/Trifecta/Result.hs, dist/build/Text/Trifecta/Result.o )
    [12 of 13] Compiling Text.Trifecta.Parser ( src/Text/Trifecta/Parser.hs, dist/build/Text/Trifecta/Parser.o )
    [13 of 13] Compiling Text.Trifecta    ( src/Text/Trifecta.hs, dist/build/Text/Trifecta.o )
    In-place registering trifecta-1.5...
    Installing library in /home/ubuntu/.cabal/lib/trifecta-1.5/ghc-7.6.3
    Registering trifecta-1.5...
    Installed trifecta-1.5

Tried to build again:

    make

Failed (same as [in this issue comment](https://github.com/nwf/dyna/issues/80#issuecomment-78330001)):

    alex --version 2>/dev/null >/dev/null || cabal install alex
    happy --version 2>/dev/null >/dev/null || cabal install happy
    cabal install --user --enable-tests --only-dependencies .
    
    Resolving dependencies...
    All the requested packages are already installed:
    Use --reinstall if you want to reinstall anyway.
    mkdir -p `dirname dist/VERSION`
    echo "Version: Dyna 0.4 pre-release" `git describe --all` > dist/VERSION
    echo "Build date:" `date` >> dist/VERSION
    echo "Commit: https://github.com/nwf/dyna/commit/"`git rev-parse HEAD` >> dist/VERSION
    cabal configure --user
    Resolving dependencies...
    Configuring dyna-0.4...
    cabal build
    Building dyna-0.4...
    Preprocessing executable 'dyna' for dyna-0.4...
    
    src/Dyna/Analysis/Mode/Execution/Functions.hs:13:14:
        Unsupported extension: AllowAmbiguousTypes
    make: *** [build] Error 1

Any advice?

More info about the installed packages is [here](https://gist.github.com/stuhlmueller/e8cbc0720238d95013d7).

**Comment by nwf** [comment]
I was able to reproduce everything (thanks for the very detailed instructions) and believe that things are now better as of commit d994f13.  Let me know if I have missed something, and enjoy playing with the prototype. :)

**Comment by stuhlmueller** [comment]
Running `make` still failed at the very end, maybe because I didn't install graphviz, or maybe because I only ran `easy_install path.py` after `make`:

    ...
    src/Dyna/Main/Driver.hs:313:1: Warning:
        Top-level binding with no type signature:
          renderFailedQuery :: forall e t.
                               (Actions t -> Doc e) -> (Rule, PBCError t) -> Doc e
    
    src/Dyna/Main/Driver.hs:422:38: Warning: Defined but not used: `r'
    Linking dist/build/dyna/dyna ...
    which sphinx-build >/dev/null && (cd docs/sphinx; make html)
    make: *** [sphinxbuild] Error 1

However, the tests pass (apart from graphviz, which I didn't install), and the interactive command line tool works, so this issue is resolved. Thanks a lot!

**Comment by jeisner** [comment]
Is Darcey's tutorial packaged with the distro?

**Comment by timvieira** [comment]
There is a "port" of the tutorial in the sphinx docs -> docs/sphinx/tutorial/darcey.rst

**Comment by timvieira** [comment]
Best viewed on http://dyna.readthedocs.org/en/latest/tutorial/darcey/

**Comment by jeisner** [comment]
Good.  When people install the distro, does the makefile print any messages
that point them to the documentation (or open it)?  Or does the README do
this?

**Comment by timvieira** [comment]
Links to the tutorial appear in the README and on the first page of the docs http://dyna.readthedocs.org/en/latest/
