### ISSUE TITLE
Builds but won't run: "No module named IPython.frontend.terminal.embed"

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [nwf/dyna#82]
The README says to "Run the python backend interactively" by doing this:
```
jeff@jbb-lenovo:~/code/dyna$  ./dyna -i examples/papa2.dyna
```

When I do, I get this:
```
Traceback (most recent call last):
  File "./src/Dyna/Backend/Python/main.py", line 2, in <module>
    from utils import path
  File "/home/jeff/code/dyna/src/Dyna/Backend/Python/utils.py", line 7, in <module>
    from IPython.frontend.terminal.embed import InteractiveShellEmbed
ImportError: No module named IPython.frontend.terminal.embed
```

# Installation details

I'm using KUbuntu (that's an Ubuntu distribution with KDE) version 16.04.

## I installed Dyna using Stack

I used Stack, not (per the README) Cabal. I ran stack init, stack setup, stack build. During one or two of those steps I had to add the --solver option, because Dyna relies on a few packages which (I guess) are not on Stackage.

## I installed iPython using Nix

I think it's just like a normal installation, though:

```
jeff@jbb-lenovo:~/code/datalog$ ipython
Python 2.7.14 (default, Sep 16 2017, 17:49:51) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: exit
jeff@jbb-lenovo:~/code/datalog$ 
```

**Comment by nwf** [comment]
Hey!  Thanks for wanting to play with our old code.  You should be aware that this is all in the process of being replaced with superior implementations, and I apologize that I haven't stayed on top of changes in upstreams that we used to build this one.

@timvieira is likely the right person for Python woes.

**Comment by timvieira** [comment]
This is an IPython version issue. `IPython.frontend.terminal.embed` has moved several times in the past couple of years.

**Here is a patch:**

Replace the code block at 
https://github.com/nwf/dyna/blob/master/src/Dyna/Backend/Python/utils.py#L4

with

```python
try:
    from IPython import embed as ip
except ImportError:
    try:
        from IPython.frontend.terminal.embed import InteractiveShellEmbed
    except ImportError:
        from IPython.terminal.embed import InteractiveShellEmbed

    def ip(banner1='', **kw):
        shell = InteractiveShellEmbed.instance(banner1=banner1, **kw)
        shell(header='', stack_depth=2)
```

**Comment by timvieira** [comment]
Also, apologies for only answering this now! Somehow I stopped getting alerts on this repo :-(
